# tasks file for kibatic.traefik
---
- name: Ensure install & config directory exists
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ traefik_install_dir }}"
    - "{{ traefik_config_dir }}"

- name: Download Traefik binary
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0755
  notify: restart traefik
  with_items:
    - url: "{{ traefik_binary_url }}"
      dest: "{{ traefik_bin_path }}"

- name: Copy traefik config file
  template:
    src: "{{ traefik_template }}.j2"
    dest: "{{ traefik_config_dir }}/{{ traefik_config_file }}"
    owner: root
    group: root
    mode: 0744
  notify: restart traefik
  tags: traefik_config

- name: Create traefik systemd unit
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - url: "{{ traefik_systemd_unit }}"
      dest: "{{ traefik_bin_path }}"
  notify: restart traefik
  tags: traefik_config
